export OS_PROJECT_DOMAIN_NAME=domainname		# replace with your domain name
export OS_USER_DOMAIN_NAME=domainname			# replace with your domain name
export OS_PROJECT_NAME=projectname				# replace with your project name again
export OS_USERNAME=username						# replace with your user name
export OS_PASSWORD=MyPassword					# replace with password of your user
export OS_AUTH_URL=https://eu4-cloud.virtuozzo.com:5000/v3  # replace with the URL of your self-service panel
export OS_IDENTITY_API_VERSION=3
export OS_AUTH_TYPE=password
export OS_INSECURE=true
export PYTHONWARNINGS="ignore:Unverified HTTPS request is being made"
export NOVACLIENT_INSECURE=true
export NEUTRONCLIENT_INSECURE=true
export CINDERCLIENT_INSECURE=true
export OS_PLACEMENT_API_VERSION=1.22
export CLIFF_FIT_WIDTH=1